baseURL = "http://example.org/"
title = "Céus do Sul"
theme = "ananke"
canonifyURLs = true
SectionPagesMenu = "main"

DefaultContentLanguage = "en"


[languages]
 [languages.en]
  languageName = "English"
# [languages.pt]
#  languageName = "Português"
 [languages.de]
  languageName = "Deutsch"
# [languages.nl]
#  languageName = "Nederlands"
#  [languages.nl.params]
#   [languages.nl.params.navigation]

disableLanguages = ["pt", "nl" ]

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[params]
 DateForm = "2006.2.1"
 date_format = "2006.2.1"
 favicon = "x"
 facebook = "https://facebook.com/ceusdosul"
 twitter = "https://twitter.com/ceusdosul"
 featured_image = "/images/david_astronomia-57.jpg"
 body_classes = "avenir bg-near-white"
 MetaKW = "Stargazing,Astronomy,Telescopes,Astrotourism,Astroturismo,Algarve,Mobile Observatory,Vacation,Holidays,Guided Astronomical Tours,Sky Observation,Dark Skies"
 MetaDesc = "Spend your vacation in the Algarve stargazing with our mobile observatory. Get a guided tour along the skies seeing planets, clusters, nebulae and galaxies. Find upcoming dates in our agenda or book a night with us directly"
[params.navigation]
