baseURL = "http://example.org/"
title = "Céus do Sul"
theme = "ananke"
canonifyURLs = true
SectionPagesMenu = "main"

DefaultContentLanguage = "en"


[languages]
 [languages.en]
  languageName = "English"
 [languages.pt]
  languageName = "Português"
 [languages.de]
  languageName = "Deutsch"
# [languages.nl]
#  languageName = "Nederlands"
#  [languages.nl.params]
#   [languages.nl.params.navigation]

disableLanguages = [ "nl" ]

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[params]
 DateForm = "2006.2.1"
 date_format = "2006.2.1"
 favicon = "x"
# facebook = "https://facebook.com/ceusdosul"
# instagram = "https://instagram.com/ceusdosul"
 featured_image = "/images/david_astronomia-57.jpg"
 body_classes = "avenir bg-near-white"
 MetaKW = "Stargazing,Astronomy,Telescopes,Algarve,Mobile Observatory,Sky Observation,Dark Skies"
 MetaDesc = "Algarve stargazing in a mobile observatory." 
[params.navigation]
